Dùng numpy để tạo các ma trận sau::

	array([[ 0,  1,  2,  3,  4,  5],
	       [10, 11, 12, 13, 14, 15],
	       [20, 21, 22, 23, 24, 25],
	       [30, 31, 32, 33, 34, 35],
	       [40, 41, 42, 43, 44, 45],
	       [50, 51, 52, 53, 54, 55]])


	array(  [[0., 0., 0., 0., 0.],
			 [2., 0., 0., 0., 0.],
			 [0., 3., 0., 0., 0.],
			 [0., 0., 4., 0., 0.],
			 [0., 0., 0., 5., 0.],
			 [0., 0., 0., 0., 6.]])

## 1

In [2]:
import numpy as np

In [4]:
import matplotlib.pyplot as plt

In [9]:
ar = np.arange(0, 60).reshape(6, -1)[:, :6]
ar

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

## 2

In [13]:
arr = np.arange(1, 61).reshape(6, -1)[:, :6]
arr

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16],
       [21, 22, 23, 24, 25, 26],
       [31, 32, 33, 34, 35, 36],
       [41, 42, 43, 44, 45, 46],
       [51, 52, 53, 54, 55, 56]])

In [14]:
arr_eye = np.eye(6)
arr_eye

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [15]:
np.mod(arr*arr_eye, 10)[:, 1:]

array([[0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0.],
       [0., 0., 4., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 6.]])